/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function sum(a: number, b: number): number
export declare function parseConfig(conf: string): number
export declare function runNetworkService(conf: string): number
export interface NetworkInfo {
  key: string
  value: string
}
export declare function collectNetworkInfos(): Array<NetworkInfo>
